# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

services:
  freshroute:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - path: .env
        required: false
    environment:
      CUOPT_BASE_URL: ""
